name: Linters

on: pull_request

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint:js
      - name: stylelint
        run: npm run lint:css